Traceback (most recent call last):
  File "/home/vviswanathan/mypython/bin/pip", line 10, in <module>
    sys.exit(main())
  File "/home/vviswanathan/mypython/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 71, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/home/vviswanathan/mypython/lib/python3.7/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/home/vviswanathan/mypython/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/vviswanathan/mypython/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 15, in <module>
    from pip._internal.cli.req_command import RequirementCommand, with_cleanup
  File "/home/vviswanathan/mypython/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 19, in <module>
    from pip._internal.network.session import PipSession
  File "/home/vviswanathan/mypython/lib/python3.7/site-packages/pip/_internal/network/session.py", line 20, in <module>
    from pip._vendor.cachecontrol import CacheControlAdapter
  File "/home/vviswanathan/mypython/lib/python3.7/site-packages/pip/_vendor/cachecontrol/__init__.py", line 9, in <module>
    from .wrapper import CacheControl
  File "/home/vviswanathan/mypython/lib/python3.7/site-packages/pip/_vendor/cachecontrol/wrapper.py", line 1, in <module>
    from .adapter import CacheControlAdapter
  File "/home/vviswanathan/mypython/lib/python3.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 9, in <module>
    from .filewrapper import CallbackFileWrapper
ModuleNotFoundError: No module named 'pip._vendor.cachecontrol.filewrapper'
Traceback (most recent call last):
  File "/home/vviswanathan/mypython/bin/pip", line 10, in <module>
    sys.exit(main())
  File "/home/vviswanathan/mypython/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 71, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/home/vviswanathan/mypython/lib/python3.7/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/home/vviswanathan/mypython/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/vviswanathan/mypython/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 15, in <module>
    from pip._internal.cli.req_command import RequirementCommand, with_cleanup
  File "/home/vviswanathan/mypython/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 20, in <module>
    from pip._internal.operations.prepare import RequirementPreparer
  File "/home/vviswanathan/mypython/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 27, in <module>
    from pip._internal.network.lazy_wheel import (
ModuleNotFoundError: No module named 'pip._internal.network.lazy_wheel'
slurmstepd: error: *** JOB 9890276 ON swarm012 CANCELLED AT 2021-02-23T01:38:54 ***
slurmstepd: error: *** JOB 9890275 ON swarm011 CANCELLED AT 2021-02-23T01:39:00 ***
slurmstepd: error: *** JOB 9890274 ON swarm009 CANCELLED AT 2021-02-23T01:39:04 ***
